### ISSUE TITLE
java.security.InvalidKeyException: Illegal key size

### ISSUE THREAD

**Issue by jdmendez** [EliteAndroidApps/WhatsApp-Crypt12-Decrypter#3]
Error while decrypting Android-derived whatsap crypt12 file, on Windows 7 (CMD.exe prompt java -jar decrypt12.jar)

Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoa
der.java:58)
Caused by: java.security.InvalidKeyException: Illegal key size
        at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1039)
        at javax.crypto.Cipher.init(Cipher.java:1393)
        at javax.crypto.Cipher.init(Cipher.java:1327)
        at decrypt12.decrypt12.decrypt(decrypt12.java:94)
        at decrypt12.decrypt12.main(decrypt12.java:146)
        ... 5 more

It seems java is not formating the KeyFile Content properly.

**Comment by EliteAndroidApps** [comment]
This is because you do not have unlimited strength jurisdiction policy files installed.

Install one of the following:

[Java 6 Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy Files ](http://www.oracle.com/technetwork/java/javase/downloads/jce-6-download-429243.html)
[Java 7 Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy Files ](http://www.oracle.com/technetwork/java/javase/downloads/jce-7-download-432124.html)
[Java 8 Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy Files ](http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html)

Extract them to: **${java.home}/jre/lib/security/**

**Comment by QuangMuop** [comment]
I use java 1.8.0_121, already download jce8 and extracted its to ${java.home}/jre/lib/security/ but the exception InvalidKeyException still occur. How can I do to resolve this? 
Thanks
